In [1]:
import pandas as pd
import numpy as np
import pykitti

In [2]:
basedir = 'dataset/'
sequence = '00'
drive = '0019'
data = pykitti.odometry(basedir, sequence)

In [3]:
len(data)

4541

In [4]:
len(list(data.velo))

6

In [5]:
for i, velodata in enumerate(data.velo):
    df = pd.DataFrame(velodata, columns=['x', 'y', 'z', 'reflectance'])
    df = df.drop(columns=['reflectance'])
    ref_series = pd.Series(np.ones((len(df)), dtype=np.float32), name='reference')
    df = pd.concat((df, ref_series), axis=1)
    print(i, df.shape)

0 (124668, 4)
1 (124605, 4)
2 (124478, 4)
3 (124167, 4)
4 (123969, 4)
5 (123924, 4)


In [11]:
df.describe()

x              y              z  reference
count  123924.000000  123924.000000  123924.000000   123924.0
mean       -1.278023       1.219171      -1.164525        1.0
std        13.982530       9.039235       0.849468        0.0
min       -77.548553     -41.430107     -10.202361        1.0
25%        -5.962987      -5.930773      -1.789791        1.0
50%        -0.004850       0.440319      -1.546659        1.0
75%         5.130324       7.070337      -0.597807        1.0
max        78.125435      44.004108       2.881527        1.0

In [6]:
pose = data.poses[0]
pose

array([[ 1.000000e+00,  9.043680e-12,  2.326809e-11,  5.551115e-17],
       [ 9.043683e-12,  1.000000e+00,  2.392370e-10,  3.330669e-16],
       [ 2.326810e-11,  2.392370e-10,  9.999999e-01, -4.440892e-16],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [7]:
pose[:3, :3]

array([[1.000000e+00, 9.043680e-12, 2.326809e-11],
       [9.043683e-12, 1.000000e+00, 2.392370e-10],
       [2.326810e-11, 2.392370e-10, 9.999999e-01]])

In [8]:
pose[:, 3]

array([ 5.551115e-17,  3.330669e-16, -4.440892e-16,  1.000000e+00])

In [9]:
vars(data).keys()

dict_keys(['sequence', 'sequence_path', 'pose_path', 'frames', 'imtype', 'cam0_files', 'cam1_files', 'cam2_files', 'cam3_files', 'velo_files', 'calib', 'timestamps', 'poses'])